spring.application.name=hooplab
server.port=8080
server.tomcat.connection-timeout=300000
spring.mvc.async.request-timeout=300000

data.base-url=${DATA_BASE_URL:http://localhost:8000}

springdoc.swagger-ui.path=/swagger-ui.html

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
